inherit_from: .rubocop_todo.yml
require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "spec/dummy/db/*"
    - "spec/dummy/config/*"
    - "doorkeepper/**/*"
    - "gemfiles/*.gemfile"

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - doorkeeper-mongodb.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3

Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/TrailingEmptyLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading
Layout/LineLength:
  Exclude:
    - spec/**/*
  Max: 100
