language: ruby
sudo: false
cache: bundler

before_install:
  - gem install bundler -v '~> 1.10'

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

env:
  - RAILS=5.0.7
  - RAILS=5.1.6
  - RAILS=5.2.0

gemfile:
  - gemfiles/Gemfile.mongoid4.rb
  - gemfiles/Gemfile.mongoid5.rb
  - gemfiles/Gemfile.mongoid6.rb
  - gemfiles/Gemfile.mongoid7.rb

services:
  - mongodb

matrix:
  exclude:
    - env: RAILS=5.0.7
      rvm: 2.1
    - env: RAILS=5.1.6
      rvm: 2.1
    - env: RAILS=5.2.0
      rvm: 2.1

    # Mongoid4 requires activemodel ~> 4.0
    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: RAILS=5.0.7
    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: RAILS=5.1.6
    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: RAILS=5.2.0

    # Mongoid5 requires activemodel ~> 4.0
    - gemfile: gemfiles/Gemfile.mongoid5.rb
      env: RAILS=5.0.7
    - gemfile: gemfiles/Gemfile.mongoid5.rb
      env: RAILS=5.1.6
    - gemfile: gemfiles/Gemfile.mongoid5.rb
      env: RAILS=5.2.0

      # Mongoid6 requires activemodel ~> 5.0
    - gemfile: gemfiles/Gemfile.mongoid6.rb
      rvm: 2.1

     # Mongoid7 requires activemodel ~> 5.1
    - gemfile: gemfiles/Gemfile.mongoid7.rb
      env: RAILS=5.0.7
    - gemfile: gemfiles/Gemfile.mongoid7.rb
      rvm: 2.1
